kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-claim
  namespace: k8samp
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi